from genweb6.core.portlets.multiviewcollection.multiviewcollection import IMultiviewCollectionPortlet
from genweb6.core.portlets.multiviewcollection.multiviewcollection import Assignment
from genweb6.core.portlets.multiviewcollection.multiviewcollection import Renderer
from genweb6.core.portlets.multiviewcollection.multiviewcollection import AddForm
from genweb6.core.portlets.multiviewcollection.multiviewcollection import EditForm
